### PR TITLE
Prepare for FastBoot 1.0

### LINKED ISSUE #76: Fix breaking changes in FastBoot 1.0
The current `ember-cli-fastboot` releases (1.0.0-rc.1 and above) introduce breaking changes. These will most likely break your current FastBoot implementation.

See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387 for more information and a guide on how to fix your addon. Also you may want to visit the `-fastboot` Slack channel to get help from other users.

*Note: this issue has been created automatically, by searching for certain patterns in your code. If you think this has been falsely created, feel free to close!*

### PR DESCRIPTION
**Pull request by josemarluedke**
ember-fastboot/ember-cli-fastboot#387

Fixes #76.

### CODE REVIEW

**Comment by binhums** [comment]
This looks great @josemarluedke, thanks for putting it together. Have you tested it?

**Comment by josemarluedke** [comment]
Yes, I tested out by adding `ember-cli-fastboot` to the dummy app and booting it up. Works gray.

**Comment by binhums** [comment]
Super, you're the best.

**Comment by binhums** [comment]
Released in [v1.3.0](https://github.com/binhums/ember-cli-bugsnag/releases/tag/v1.3.0), made a minor jump because of the upgrade to bugsnag.js library. Thanks again.

**Pull request merged**
