### PR TITLE
Added yarn.lock

### PR DESCRIPTION
**Pull request by josex2r**
Added `yarn.lock` file to the project root.

[CircleCI report](https://circleci.com/gh/BBVAEngineering/ember-cli-bugsnag/3)

### CODE REVIEW

**Comment by binhums** [comment]
Thanks! :+1: Are you planning to do some development work on ember-cli-bugsnag?

**Comment by josex2r** [comment]
Currently we have a fork in our company [BBVAEngineering/ember-cli-bugsnag](https://github.com/BBVAEngineering/ember-cli-bugsnag/tree/merge-upstream) because we have some custom changes.
If we introduce some new and useful stuff we will open a PR :)

**Comment by binhums** [comment]
Make sense. Let me know if you want to work together on anything.





On Mon, Feb 20, 2017, at 04:21 PM, Jose wrote:

> Currently we have a fork in our company BBVAEngineering/ember-cli-
> bugsnag[1] because we have some custom changes.
>  If we introduce some new and useful stuff we will open a PR :)



> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
> 




Links:

  1. https://github.com/BBVAEngineering/ember-cli-bugsnag/tree/merge-upstream
  2. https://github.com/binhums/ember-cli-bugsnag/pull/68#issuecomment-281121794

**Comment by binhums** [comment]
Actually what would be super useful as part of this change is to update the `circle.yml` to install using yarn. Instructions are here:

https://circleci.com/docs/yarn/

**Pull request merged**
