### PR TITLE
Allow setting a custom error name on exceptions

### PR DESCRIPTION
**Pull request by rlivsey**

### CODE REVIEW

**Comment by binhums** [comment]
Hi @rlivsey thanks for the contribution. How are you using this yourself, why do you need custom error names? Could you provide an example definition of the util?

This looks sensible, have you got a screenshot of what the result looks like on bugsnag?

We'd need documentation and preferrably some tests to accept this.

**Comment by rlivsey** [comment]
Hi @binhums 

As [mentioned in the bugsnag docs](https://docs.bugsnag.com/platforms/browsers/#reporting-handled-exceptions), a lot of the time the name of the JS error is simply `Error` so they all get bundled together.

To get around that, we also append the `error.message` so that our Bugsnag errors look like:

screen shot 2016-08-02 at 09 19 34

We previously had a hack where we were mutating the error in `getMetaData` as so:

```js
export function getMetaData(error, container) {
  // mutate the error as a side effect
  error.name = error.name + ' | ' + error.message;
  return {
    // plus additional info
  };
}
```

This "worked" but in recent builds of Chrome you couldn't set `error.name` which made me look at making this PR, so now we can do:

```js
export function getErrorName(error, container) {
  return error.name + ' | ' + error.message;
}
```

I'll happily update the README docs etc… if you're happy with the design. As far as tests go, there don't seem to be any existing ones, do you have any thoughts on the best way to test this?

Cheers.

**Comment by binhums** [comment]
Agreed, this seems reasonable, however I'd rather make sure that good names are reported for everyone than introduce a feature for customization. My feelings are that the addon should provide good enough error names out of the box.

Are these Ember specific errors that are not providing you with enough information or are they from the browser?

Can you give me an example of the kind of errors that you're getting that are not descriptive enough? Is the problem that similar errors are grouped together in Bugsnag?

I'd be happy to talk about this more in a call if you wanted

**Comment by binhums** [comment]
Ok I've had a look at how we're seeing errors come through, I see what your describing. The error description itself still appears in the UI on the next line.

What is it about the errors having the same name that doesn't work for you?

**Comment by rlivsey** [comment]
It looks like it's possible to [set a custom `groupingHash`](https://docs.bugsnag.com/platforms/browsers/reporting-handled-errors/#changing-error-grouping-on-the-bugsnag-dashboard) which determines how the errors are grouped and may be a better approach than customizing the error name.

I might be possible to extract the current Route / component the error came from or something and use that to build the `groupingHash` vs it relying on file path & line number, which the docs say is how grouping works by default & may be brittle with minification etc unless source maps are used?

**Comment by binhums** [comment]
Concluded that this appears to be unreliably grouping errors together because in minified source we have the same filename and file number that the error is occurring in.

I see the potential solutions as:

- Specifying `groupingHash` to include information about the source as you've suggested, or
- Configuring Bugsnag to work with the sourcemap.

I think that some of our apps do have sourcemaps uploaded to Bugsnag, it is [possible to do this as part of CI](http://blog.bugsnag.com/upload-sourcemaps) but it's not a very good standard answer to everyone using `ember-cli-bugsnag`.

I like the paradigm of `ember install ember-cli-bugsnag` and things just work so if we can come up with something that works well out of the box then that is good news.

**Comment by binhums** [comment]
@rlivsey were you able to get this working in the end with sourcemaps? I'm happy to explore getting this merged if it's something that you've found you need.

**Comment by binhums** [comment]
@rlivsey I'm going to close this pull request because:

1. we identified better solutions for the grouping problem you're experiencing, and
2. the pull request is inactive.

Latest word on the street is that there is an [ember-cli-deploy plugin currently under development](https://github.com/IcarusWorks/ember-cli-deploy-bugsnag) for uploading sourcemaps to bugsnag.

Best of luck.

**Comment by rlivsey** [comment]
👍

**Pull request closed without merging**
