### PR TITLE
Use a shim for bugsnag

### LINKED ISSUE #21: CSP inline-script error
Chrome gives the following CSP error when using the addon:

```
[Report Only] Refused to execute inline script because it violates the following 
Content Security Policy directive: "script-src ... ". Either the 'unsafe-inline' keyword, 
a hash ('sha256-Li1kX2hSsXxBIvK1YWeekOV49Asr5QAOvrIrILWqql0='), or a 
nonce ('nonce-...') is required to enable inline execution.
```

It would be reasonably straightforward to generate a hash of the contents and inject that into the CSP rules in development, but I'm not sure how this would work in production. Obviously the addon doesn't integrate with the web-server in any way so there'd be no way of injecting this.

Adding a nonce to the config and using that in the script tag would also work, we'd just need to use the same nonce in the web-server config for it to work on live.

Another approach would be to not inject the script tag into the HTML at build time at all and instead dynamically inject the script at run-time using something like [ember-inject-script](https://github.com/minutebase/ember-inject-script).

### PR DESCRIPTION
**Pull request by binhums**
Moves plugin to use a vendor shim file to import Bugsnag libraries through bower:

- Allows projects to be run offline
- Prevents content security violations (fixes #21)

N.B. Drops support for the releaseUrl config option.

@twokul can I get your thoughts on this approach. In principle this is done, I need to do more testing here before I can confidently release. Should be a minor release and not a patch release.

See https://github.com/ember-cli-reporter/ember-cli-reporter-bugsnag for some of my wider thoughts on where we could take this.

### CODE REVIEW

**Comment by binhums** [comment]
Ok this is ready to go. Will merge if no-one has any comments.

**Comment by timiyay** [comment]
@binhums gave this a spin in my app, but no love. Crashed out during build:

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/me/MyApp/tmp/source_map_concat-input_base_path-sUbSEwkI.tmp/0/bower_components/bugsnag/src/bugsnag.js'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at ConcatWithMaps.keyForFile (/Users/me/MyApp/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/me/MyApp/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/me/MyApp/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/me/MyApp/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/me/MyApp/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/me/MyApp/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/me/MyApp/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/Users/me/MyApp/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/Users/me/MyApp/node_modules/broccoli-caching-writer/index.js:21:10)
    at new ConcatWithMaps (/Users/me/MyApp/node_modules/broccoli-concat/concat.js:22:17)
    at module.exports (/Users/me/MyApp/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/me/MyApp/node_modules/ember-cli/lib/broccoli/ember-app.js:348:10)
    at EmberApp.javascript (/Users/me/MyApp/node_modules/ember-cli/lib/broccoli/ember-app.js:1214:12)
    at EmberApp.toArray (/Users/me/MyApp/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
    at EmberApp.toTree (/Users/me/MyApp/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/Users/me/MyApp/ember-cli-build.js:82:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/Users/me/MyApp/node_modules/ember-cli/lib/models/builder.js:54:19)

```

**Comment by binhums** [comment]
That's embarrassing. I'll tidy up.

**Comment by binhums** [comment]
did you do a bower install?

**Comment by binhums** [comment]
Tracking branch got busted with repo move, closing and reopening.

**Comment by binhums** [comment]
Released in https://github.com/binhums/ember-cli-bugsnag/releases/tag/v1.0.0

**Pull request closed without merging**
